"""Initial migration

Revision ID: 571d99c7345f
Revises: 
Create Date: 2024-10-30 00:26:42.546200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d99c7345f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('cod_banco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_banco', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('cod_banco')
    )
    op.create_table('cliente',
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=True),
    sa.Column('telefone_cliente', sa.String(length=15), nullable=True),
    sa.Column('endereco_cliente', sa.Text(), nullable=True),
    sa.Column('email_cliente', sa.String(length=255), nullable=True),
    sa.Column('senha_cliente', sa.String(length=128), nullable=True),
    sa.Column('ultimo_login_cliente', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('cpf_cnpj')
    )
    op.create_table('tipo_arquivo',
    sa.Column('id_tipo_arquivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_arquivo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_arquivo')
    )
    op.create_table('tipo_erro',
    sa.Column('id_erro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_erro', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_erro')
    )
    op.create_table('tipo_nf',
    sa.Column('id_tipo_nf', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_nf', sa.String(length=100), nullable=True),
    sa.Column('modelo_nf', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_nf')
    )
    op.create_table('arquivo',
    sa.Column('id_arquivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tipo_arquivo', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('data_hora_upload_arquivo', sa.DateTime(), nullable=True),
    sa.Column('tipo_arquivo', sa.String(length=50), nullable=True),
    sa.Column('url_minio_arquivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cpf_cnpj'], ['cliente.cpf_cnpj'], ),
    sa.ForeignKeyConstraint(['id_tipo_arquivo'], ['tipo_arquivo.id_tipo_arquivo'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('extrato_ofx',
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('cod_banco', sa.Integer(), nullable=False),
    sa.Column('num_agencia_extrato', sa.Integer(), nullable=True),
    sa.Column('num_conta_extrato', sa.Integer(), nullable=True),
    sa.Column('data_inicial_extrato', sa.Date(), nullable=True),
    sa.Column('data_final_extrato', sa.Date(), nullable=True),
    sa.Column('saldo_inicial_extrato', sa.Float(), nullable=True),
    sa.Column('saldo_final_extrato', sa.Float(), nullable=True),
    sa.Column('id_arquivo_par', sa.Integer(), nullable=True),
    sa.Column('data_verificacao_extrato', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cod_banco'], ['banco.cod_banco'], ),
    sa.ForeignKeyConstraint(['id_arquivo'], ['arquivo.id_arquivo'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('extrato_pdf',
    sa.Column('cod_banco', sa.Integer(), nullable=False),
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('num_agencia_extrato', sa.Integer(), nullable=True),
    sa.Column('num_conta_extrato', sa.Integer(), nullable=True),
    sa.Column('data_inicial_extrato', sa.Date(), nullable=True),
    sa.Column('data_final_extrato', sa.Date(), nullable=True),
    sa.Column('saldo_inicial_extrato', sa.Float(), nullable=True),
    sa.Column('saldo_final_extrato', sa.Float(), nullable=True),
    sa.Column('id_arquivo_par', sa.Integer(), nullable=True),
    sa.Column('data_verificacao_extrato', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cod_banco'], ['banco.cod_banco'], ),
    sa.ForeignKeyConstraint(['id_arquivo'], ['arquivo.id_arquivo'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('nota_fiscal',
    sa.Column('id_tipo_nf', sa.Integer(), nullable=False),
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('num_nota', sa.Integer(), nullable=True),
    sa.Column('data_emissao_nota', sa.Date(), nullable=True),
    sa.Column('valor_nota', sa.Float(), nullable=True),
    sa.Column('cnpj_emitente_nota', sa.String(length=14), nullable=True),
    sa.Column('cnpj_destinatario_nota', sa.String(length=14), nullable=True),
    sa.Column('nota_verificada', sa.Boolean(), nullable=True),
    sa.Column('data_verificacao_nota', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_arquivo'], ['arquivo.id_arquivo'], ),
    sa.ForeignKeyConstraint(['id_tipo_nf'], ['tipo_nf.id_tipo_nf'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    op.create_table('validacao',
    sa.Column('id_arquivo', sa.Integer(), nullable=False),
    sa.Column('id_erro', sa.Integer(), nullable=False),
    sa.Column('status_validacao', sa.Boolean(), nullable=True),
    sa.Column('data_hora_validacao', sa.DateTime(), nullable=True),
    sa.Column('checksum_validacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_arquivo'], ['arquivo.id_arquivo'], ),
    sa.ForeignKeyConstraint(['id_erro'], ['tipo_erro.id_erro'], ),
    sa.PrimaryKeyConstraint('id_arquivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validacao')
    op.drop_table('nota_fiscal')
    op.drop_table('extrato_pdf')
    op.drop_table('extrato_ofx')
    op.drop_table('arquivo')
    op.drop_table('tipo_nf')
    op.drop_table('tipo_erro')
    op.drop_table('tipo_arquivo')
    op.drop_table('cliente')
    op.drop_table('banco')
    # ### end Alembic commands ###
